### ISSUE TITLE
Niching

### ISSUE THREAD

**Issue by mc-cat-tty** [ITIS-Enrico-Fermi/PlanarEvolvedAntenna#6]
> Deriva cromosomica

 1. Estrazione individuo random
 2. Selezione del suo intorno
 3. Estrazione individui con probabilità proporzionale alla fitness
 4. Sostituzione individuo più debole

**Comment by giuliocorradini** [comment]
Dobbiamo definire come potare le soluzioni esterne alla regione ammissibile.
Inoltre lanciare la simulazione col debugger genera una popolazione dove tutti i geni hanno fitness $-\infty$, quindi da controllare
